import 'reflect-metadata';
import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { randomBytes, randomUUID } from 'node:crypto';
import { NestFactory } from '@nestjs/core';
import { INestApplication } from '@nestjs/common';
import { AppModule, ApiErrors, Services } from '../src/api/app';
import { migrate } from '../src/infra/migrate';
import { LOCATIONS } from '../shared/game';
const name=process.env.TEST_DB_NAME;
if(!name||!/^\w+_test$/.test(name)) throw new Error('Set TEST_DB_NAME ending in _test');
let app:INestApplication, base:string;
const key=randomBytes(32).toString('hex'), admin=randomBytes(32).toString('hex');
before(async()=>{process.env.DB_NAME=name;process.env.BRIDGE_KEY=key;process.env.ADMIN_KEY=admin;process.env.REDIS_URL='';app=await NestFactory.create(AppModule,{logger:false});app.useGlobalFilters(new ApiErrors());await migrate(app.get(Services).db);await app.listen(0,'127.0.0.1');base=await app.getUrl();});
after(async()=>{await app?.close();});
test('HTTP health, key boundaries and authenticated action flow',async()=>{
  assert.equal((await fetch(base+'/health')).status,200);
  assert.equal((await fetch(base+'/admin/overview')).status,403);
  assert.equal((await fetch(base+'/admin/overview',{headers:{'x-admin-key':key}})).status,403);
  assert.equal((await fetch(base+'/admin/overview',{headers:{'x-admin-key':admin}})).status,200);
  const post=(route:string,body:unknown,token='',bridge=key)=>fetch(base+route,{method:'POST',headers:{'content-type':'application/json','x-bridge-key':bridge,'x-session':token},body:JSON.stringify(body)});
  assert.equal((await post('/bridge/state',{},'','wrong')).status,403);
  assert.equal((await post('/bridge/state',{})).status,401);
  const credentials={username:'http_'+randomUUID().replace(/-/g,'').slice(0,16),password:'http-test-password'};
  assert.equal((await post('/bridge/register',{credentials,source:'test-http'})).status,201);
  const login=await post('/bridge/login',{credentials,source:'test-http'});assert.equal(login.status,201);const session=await login.json() as any;
  const body={action:{id:randomUUID(),type:'bank.deposit',amount:100},world:{position:LOCATIONS.bank,dimension:0,health:100,ownVehicle:false}};
  assert.equal((await post('/bridge/action',{...body,actor:999},session.token)).status,400);
  assert.equal((await post('/bridge/action',body,session.token)).status,201);
  const state=await (await post('/bridge/state',{},session.token)).json() as any;
  assert.equal(state.character.bank,100);assert.equal(state.character.cash,900);
  assert.equal(JSON.stringify(state).includes('password_hash'),false);assert.equal(JSON.stringify(state).includes('session_hash'),false);
  assert.equal((await post('/bridge/logout',{},session.token)).status,201);
  assert.equal((await post('/bridge/state',{},session.token)).status,401);
});
